volumes:
  auth-postgres_data:

services:
  auth-db:
    image: postgres:12.4
    volumes:
      - auth-postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"