version: '3'

volumes:
  auth_postgres_data:
  tickets_postgres_data:

services:
  auth-db:
    image: postgres:12.4
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
  tickets-db:
    image: postgres:12.4
    volumes:
      - tickets_postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5433:5432"
  auth-microservice:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: auth-db
    depends_on:
      - auth-db
  tickets-microservice:
    build:
      context: ./tickets
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      POSTGRES_HOST: tickets-db
    depends_on:
      - tickets-db